import type { Metadata } from "next";
import { Kode_Mono } from 'next/font/google';
import "./globals.css";
import SmoothScrolling from "@/components/SmoothScrolling";

const kodeMono = Kode_Mono({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={kodeMono.className}
      >
      <SmoothScrolling>
          {children}
      </SmoothScrolling>
      </body>
    </html>
  );
}
